label equip-1
    kernel /boot/Image
    fdt /boot/rk3528-rock-2f.dtb
    append root=PARTLABEL=rootfs rootwait rw console=ttyFIQ0,1500000n8 console=ttyS0,1500000n8 earlycon=uart8250,mmio32,0xff9f0000
